source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'DemoNetImage' do
  use_frameworks!
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'DeviceKit'
  pod 'Toast-Swift'
end
