platform :ios, '9.0'
use_frameworks!

target 'DemoAppWithPods' do
  use_frameworks!
  pod 'Material'
  pod 'SnapKit'
  pod 'Qiniu', '~> 7.2'
  pod 'VGPlayer', '~> 0.2.0'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'KeychainSwift'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'ObjectMapper'
end
